#.. _____________________ ..#
## -- // WARNING \\ -- 
## -- THIS WORK IS UNDER EXCLUSIVE COPRIGHT FOR BAITCORP LABS. DISTRIBUTION, MODIFICATION, SELLING, OR SHARING WITHOUT EXPLICIT PERMISSION FROM BAITCORP LABS IS STRICTLY PROHIBITED.
## -- THIS PROGRAM IS LICENSED FOR MODIFICATION TO AND ONLY TO: "BAITCORP LABS" [FR], "CCHOST PARIS" [FR].
## -- 
## -- ExploitsX Sebastian Giheta 2019-2020
#.. _____________________ ..#

#.. _____________________ ..#
# ___________              .__         .__  __         ____  ___              _________ .__            __   _________         
# \_   _____/__  _________ |  |   ____ |__|/  |_  _____\   \/  /     .__      \_   ___ \|  |__ _____ _/  |_ \_   ___ \  ____  
#  |    __)_\  \/  /\____ \|  |  /  _ \|  \   __\/  ___/\     /    __|  |___  /    \  \/|  |  \\__  \\   __\/    \  \/ /  _ \ 
#  |        \>    < |  |_> >  |_(  <_> )  ||  |  \___ \ /     \   /__    __/  \     \___|   Y  \/ __ \|  |  \     \___(  <_> )
# /_______  /__/\_ \|   __/|____/\____/|__||__| /____  >___/\  \     |__|      \______  /___|  (____  /__|   \______  /\____/ 
#         \/      \/|__|                             \/      \_/                      \/     \/     \/              \/        
#
# ExploitsX by Sebastian Giheta, owner of 8b8t.xyz
#.. _____________________ ..#


#
# This config is for anti-abuse measures and chat-config lists.
# and a few messages
#


#...........................#
#.. ANTI ABUSE / BACKDOOR ..#
#...........................#
# check player gamemode on inventory click (needs plugman reload or server restart)
bc-check-gamemode: true
# kill the player and clear their inventory if they are in creative and not in the whitelist?
gamemode-punish: true
# whitelisted users who can have op. (in the list below.) this will not op players, it will just
# deop them if they're not in the list and opped.
enable-op-whitelist: false
# the UUIDs are specified below
# if a player is not opped but is on this whitelist, they will not automatically be opped. this only means that they
# can KEEP their op if they already have it.
# this means NOTHING if the player is not opped.
op-whitelist-uuids:
  - 94b2a047-7436-49ef-b527-39c6f4d14bd4
# ^^^^^^ remove this and replace it with your own UUID, and add multiple lines if multiple people have the permissions.
# should players on the UUID whitelist still be able to bypass the player blocked commands list? (keep false for better security)
whitelist-can-run-commands: false
# Block these commands player-side
player-blocked-commands:
  - plugins
  - op
  - give
  - item
  - kill
  - smite
  - tp
# Block even the console from running these commands
# (commands listed here will ALSO be blocked from all players)
enable-limited-console: true
console-blocked-commands:
  - blockedcommand
  - anotherblockedcommand
# send a message when the command is blocked
bc-send-message: true
player-blocked-message: "&4Players cannot run these commands. Please use console."
console-blocked-message: "&4This command has been disabled."
#...........................#
#.. _____________________ ..#
#...........................#

#...........................#
#..  EXTRA CHAT FEATURES  ..#
#...........................#
# Send a different message on first join for a player. Removeactualjoinmsg will make this message replace the
#   default actual join message (it'll only be removed if ExploitsX is handling join/leave messages
# Firstjoinmsg is the message sent when the player leaves the server
# Use {PLAYER} and {TOTALJOINS} as placeholders. PlaceholderAPI support coming soon.
#   {TJFORMAT} will add "st", "nd" or "th" respective to the number before it
firstjoin:
  enable: false
  removeactualjoinmsg: true
  firstjoinmsg: "&c{PLAYER}&r&7 Has joined the server for the first time! They are the {TOTALJOINS}{TJFORMAT} player!"
# Allow players to use the /say command.
# Use {PREFIX} For ExploitsX prefix, {PLAYER} for the playername and {MESSAGE} for the message.
# cooldown is for the cooldown in seconds. Use {s} for the remaining seconds.
saycommand:
  enable: false
  format: "{PREFIX} &r{PLAYER} &b> &5{MESSAGE}"
  cooldown: 30
  cooldownmessage: "{PREFIX} &cYou cannot use this command for another {s} seconds."
#...........................#
#.. _____________________ ..#
#...........................#

#...........................#
#.. CONTAINER PROTECTION  ..#
#...........................#
# Containers in minecraft cause a large amount of a server's clocks, sometimes unnecessarily. Here you can ratelimit
#   or add extra checks to when they are opened
containers:
  # prevent spamming intents by opening chests
  prevent-spam: true
  # levels of severity (spam-level is the amount of opens needed per second to start cancelling packets)
  rates:
    spam-level: 4
    spam-kick: 25
  # hitting any one of these requirements will make the system start counting (even if there is just one shulker but the minimum items isn't hit it'll count)
  enablers:
    minimum-items:
      int: 4
      count-items-in-shulkers: true
    shulker: 1
    book: 1
  # items to be instantly removed upon chest click
  illegal-items:
    enable: true
    # The option below defines what to check:
    #   0: nothing
    #   1: chests, trapped chests and dispensers
    #   2: shulkers, hoppers, chests, trapped chests, dispensers, barrels, droppers
    check: 2
    items:
      - BEDROCK
      - BARRIER
      - END_PORTAL_FRAME
      - COMMAND
      - COMMAND_CHAIN
      - COMMAND_MINECART
      - COMMAND_REPEATING
      - STRUCTURE_BLOCK
      - STRUCTURE_VOID
      - CROPS
      - MOB_SPAWNER
    # valid actions:
    #   'kill' to kill the player opening the chest
    #   'kick' to kick the player
    #   'clear' to clear the player's inventory (does not include the item in the chest)
    #   'damage:X' to damage the player. Replace X with the integer damage value
    #   'remove' to remove the item completely
    #   'destroy' to delete the chest entirely
    #   'danger-check-surroundings:X:Y:Z' to check all chests around for the same item. (ASYNC, will not lag your server)
    #       Replace X with the radius of blocks around the chest to check.
    #       Replace Y with the action to do on that chest if another illegal is found.
    #       Replace Z with "loop" or "noloop" depending if you want it to repeat if it finds another illegal
    #   'reduce' to reduce the item to 1
    #   'stack' to increase the item to it's max stacksize
    actions:
      - danger-check-surroundings:2:remove:loop
      - remove
      - damage:2
    sendmessage: false
    message: "&cA disallowed item has been removed."
#...........................#
#.. _____________________ ..#
#...........................#

#...........................#
#.. CHATPROTECTION / SPAM ..#
#...........................#
# enable chat functionality and commands for ExploitsX.
enable-exploitsx-chat: true
## Chat protection
# things that will make messages seem more legit (prevents people from using fancychat etc.)
# keep this list with the most common letters / aeiou listed here:
#E – in 11.1607% words
#A – in 8.4966% words
#R – in 7.5809% words
#I – in 7.5448% words
#O – in 7.1635% words
#T – in 6.9509% words
#N – in 6.6544% words
#S – in 5.7351% words
# this will not block words that do not contain this. it'll just alert exploitsX that the user
# might not be speaking english. try adapting this with more characters if your playerbase is not english
# some commented letters are at the bottom for turkish / russian / chinese characters
enable-chat-whitelist: true
chat-whitelist:
  - e
  - a
  - r
  - i
  - o
  - t
  - n
  - s
  - l
  - c
  - h
  - u
  - y
  - d
#>> TR <<
#- İ
#- ü
#- ı
#>> RU <<
#- и
#- л
#- д
#- п
#- ы
#- ч
#- б
#- я
#- ц
#>> CN <<
#- 的
#- 一
#- 是
#- 不
#- 了
#- 人
#- 我
#- 在
#- 有
#- 他
#- 这
#- 当

## words that trigger a violation
# by default and on survey of over 6,000,000 messages we've added the most commonly used phrases / letters
# used to spam / send useless information to chat. Remove as you wish.
# these words aren't blocked. They just flag the user if they're said too much
red-flag-words:
  - be warned
  - be missed
  - fuck
  - fag
  - remember kids
  - fixing chat
  - ignore
  - nobody cares if
  - lets have a party
  - good to see you
  - got kicked
  - konas
  - obama
  - king
  - my friend
  - got kicked
  - welcome to
  - hello
  - nice to see you
  - farewell
  - later
  - ayyyy its
  - ahhh rip
  - i just mined
  - larp
  - on top
  - bartender
  - token logger
  - ᴘʜ
  - ᴡᴜʀ
  - 6g
  - 6s
  - nig
  - 32k
  - tpa
  - now
  - 0b0m
  - matrix
  - anticheat
  - mc
  - method
  - owner
  - xormios
  - currently
  - crashing
  - server
  - pebble
  - play
  - 2b
  - 4u
  - .ru
  - biz
  - grabify
  - link
  - co.uk
  - net
  - org
  - uk
  - illegal
  - impurity
  - .me
  - .co
  - tk
  - cf
  - gq
  - xyz
  - 6b
  - .ga
  - .gg
  - best
  - bypass
  - yac
  - inertia
  - recently
  - i just
  - anarchy
  - clone
  - today
  - dupe enabled
  - thanks to
  - just mined
  - just placed
  - hello,
  - farewell,
  - ！
  - popped
  - hackmc
  - «
  - yat
  - antispam
  - kys
  - mad
  - ！
  - ａ
  - ｅ
  - ｕ
  - ｏ

#...........................#
#.. _____________________ ..#
#...........................#

# please, please do not change this.
listsymlversion: 8
listsymlupdateseverity: optional

#### EXPLOITSX GHOST MODE ####
# disable all exploitsX commands apart from it's exploit fixing features. 
#   pair this with branding: false in config.yml in order to hide that you 
#   have ExploitsX enabled. Do NOT enable this if you have not spoken to Bubba#8888
#   about the implications (and heard about the ways that this can break things)

# This was initially designed for a streamer's server. If you know what I'm talking about enable this.
enable-ghost-mode: false
# put in the key that Bubba#8888 sends you after you ask him to enable this method below. (Join our support discord)
# this is just to ensure that you actually spoke to him about the implications of this
ghost-mode-confirm-code: 00000